" Steven La <mrstevenla@gmail.com>

" ----------------------------------------------------------------------------
"  Vundle
" ----------------------------------------------------------------------------

" Required setup
call plug#begin('~/.vim/plugged')

Plug 'kien/ctrlp.vim'
Plug 'bling/vim-airline'
Plug 'othree/yajs.vim'

call plug#end()

filetype plugin indent on

" ----------------------------------------------------------------------------
"  Plugin setup
" ----------------------------------------------------------------------------

" Airline settings
let g:airline_left_sep=''
let g:airline_right_sep=''

" ----------------------------------------------------------------------------
"  General settings
" ----------------------------------------------------------------------------

" Backup Options
set nobackup
set noswapfile

set hidden

" ----------------------------------------------------------------------------
"  Editing behavior
" ----------------------------------------------------------------------------

" Indentation
"set cindent
"set autoindent
set smartindent             " Smart indentation

" Tabs
set expandtab               " Space as tabs
set tabstop=2               " Real tabs are 2 spaces
set shiftwidth=2            " Autoindent width
set softtabstop=2           " When <BS>, remove this many spaces

set showcmd                 " show currently input commands
set autoread                " auto reload file changes

set pastetoggle=<leader>p   " Toggle pasting mode

" ----------------------------------------------------------------------------
"  Visual & interface options
" ----------------------------------------------------------------------------

syntax on
colorscheme noctu
set mouse=a

set ttyfast			        " fast redrawing
set scrolloff=6             " have context lines when scrolling
set cursorline              " highlight current line

set title                   " Change terminal title
set number                  " Show line numbers
set numberwidth=4           " Handles numbers up to 99999

set laststatus=2            " Enable statusbar (even for airline)
set statusline=%f\          " tail of the filename
set statusline+=%m%r%h%w
set statusline+=%=          " right align
set statusline+=%l,%c       " line,col
set statusline+=\ \ \ \ \ \ \ \ %P

" ----------------------------------------------------------------------------
"  Movement & searching behaviors
" ----------------------------------------------------------------------------

" Remap j and k to act as expected when used on long, wrapped, lines
nnoremap j gj
nnoremap k gk

set nostartofline           " cursor in same column in movement

" Search
set ignorecase              " ignore case in search
set incsearch               " incremental search
set hlsearch                " highlight search results
set smartcase               " ignore case when lowercase

" General options
set nocompatible
set encoding=utf-8
set history=1000            " I have the room for this
set undolevels=1000         " MOAR, MOAR

" ----------------------------------------------------------------------------
"  Keyboard convenience
" ----------------------------------------------------------------------------

" Easier window navigation
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" Maps
map <F1> <nop>
map Y y$
nnoremap ; :
vnoremap ; :

" Can't let go of shift quick enough? NO PROBLEM.
:command Q q
:command W w
:command Wq wq
:command WQ wq

