# Path to your oh-my-zsh configuration.
DOTFILES=$HOME/.dotfiles
ZSH=$DOTFILES/zsh/oh-my-zsh
ZSH_CUSTOM=$DOTFILES/zsh/custom

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="better_kardan"

plugins=(git virtualenv zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:/opt/local/bin:/usr/local/git/bin:/usr/local/sbin:/usr/local/mysql/bin:$HOME/.local/bin:$PATH

# tmux copy save buffer to pasteboard
alias copy="tmux saveb - | reattach-to-user-namespace pbcopy"

# Python debugging servers
alias serve="python -m SimpleHTTPServer"
alias maildebug="python -m smtpd -n -c DebuggingServer localhost:1025"

# virtualenvwrapper
export WORKON_HOME=~/Projects/env
source /usr/local/bin/virtualenvwrapper.sh 2>/dev/null
VIRTUAL_ENV_DISABLE_PROMPT=true

# Vundle
alias vundle-install='vim +BundleInstall +qall'
alias vundle-list='vim +BundleList'
alias vundle-clean='vim +BundleClean +qall'

# Latest node with harmony
# Requires n
alias harmony='n use $(n --latest) --harmony'

# Java
#export JAVA_HOME=$(/usr/libexec/java_home)

fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    bg
    zle redisplay
  else
    zle push-input
  fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z

# Local settings should override
[[ ( -f $HOME/.zshrc_local ) ]] && source $HOME/.zshrc_local
