export DOTFILES=$HOME/.dotfiles
export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/opt/local/bin:/usr/local/git/bin:/usr/local/sbin:/usr/local/mysql/bin

# Source powerline
. $DOTFILES/powerline/powerline/powerline/bindings/zsh/powerline.zsh

source $DOTFILES/zsh/completion.zsh
autoload -U compinit
compinit -C

# Tunlr on/off
alias tunlron="sudo networksetup -setdnsservers Wi-Fi 149.154.158.186, 199.167.30.144"
alias tunlroff="sudo networksetup -setdnsservers Wi-Fi"

# tmux copy save buffer to pasteboard
alias copy="tmux saveb - | pbcopy"

# Python debugging servers
alias serve="python -m SimpleHTTPServer"
alias maildebug="python -m smtpd -n -c DebuggingServer localhost:1025"

# basic command aliases
alias ..="cd .."
alias cd..="cd .."
alias ls="ls -G"

# virtualenvwrapper
export WORKON_HOME=~/Projects/env
source /usr/local/bin/virtualenvwrapper.sh
VIRTUAL_ENV_DISABLE_PROMPT=true

# Java
export JAVA_HOME=$(/usr/libexec/java_home)

fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    bg
    zle redisplay
  else
    zle push-input
  fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z

